name: Build Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    # Bắt buộc phải dùng macos-latest để build source iOS (Xcode),
    # nhưng bạn KHÔNG cần sở hữu máy Mac thật, GitHub Actions sẽ tự lo.
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: latest-stable }
      
      - name: Build Unsigned IPA (No .p12 required)
        run: |
          chmod +x ./build_unsigned.sh
          ./build_unsigned.sh
      
      - name: Prepare eSign ready IPA
        run: |
          chmod +x ./build_esign_ready_ipa.sh
          ./build_esign_ready_ipa.sh build/HYper-Regedit-Key-Enabled-unsigned.ipa
      
      - name: Upload Unsigned IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OGIOS-Unsigned-IPA
          path: build/HYper-Regedit-Key-Enabled-unsigned.ipa
